networks:
  db:
volumes:
  db-data:

services:
  app:
    extends:
      file: angular-lab-main/docker-compose.yml
      service: app
    depends_on:
      database:
        condition: service_healthy

  database:
    extends:
      file: angular-lab-main/docker-compose.yml
      service: database

  takicine:
    build:
      context: takicine/
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "4200:4200"
